name: "Test"
on: push
env:
  CYPRESS_CACHE_FOLDER: .cache/cypress

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get current Cypress version
        id: cypress-ver
        run: echo ::set-output name=cypress_version::$(yarn info cypress -A --name-only)
      - name: Cache Cypress
        uses: actions/cache@v2
        with:
          path: |
            $CYPRESS_CACHE_FOLDER
          key: cypress-binary-${{ steps.cypress-ver.outputs.cypress_version }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - name: Install dependencies
        run: yarn
      # Enable lint when all errors are fixed
      # - run: yarn run lint
      - run: yarn run prettier:ci
  type-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - name: Install dependencies
        run: yarn
      - run: yarn run typecheck
  jest-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - name: Install dependencies
        run: yarn
      - run: yarn run test --watchAll=false
  cypress-tests:
    continue-on-error: ${{ matrix.react != '17' }}
    strategy:
      fail-fast: false
      matrix:
        react: [17, 18]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - name: Install dependencies
        run: yarn
      - name: Setup react
        run: yarn up react@${{ matrix.react }} react-dom@${{ matrix.react }}
      - name: Build packages
        run: yarn run build
      - name: Cypress Core Components
        uses: cypress-io/github-action@v3
        with:
          install: false
          command: yarn run test:core-components
      - name: Cypress Lab Components
        uses: cypress-io/github-action@v3
        with:
          install: false
          command: yarn run test:lab-components
